### ISSUE TITLE
"failed to create GitHub release: Validation Failed"

### ISSUE THREAD

**Issue by carusog** [tadodotcom/gh-release-cli#2]
Github updated `@octokit/rest` API and due to some deprecations, probably, more specifically `timeout` ones, we are getting a build fail on Jenkins.

See https://cloudci.tado.com/job/webapp2018-build-release/225/console for a failed build example.

**Comment by carusog** [comment]
@weezner Let's add this to next planning.

**Comment by Marcel-Malus** [comment]
**Short Version:**
It is an unfixed bug and no good workaround was found. Solution: Either delete branches immediately after merging the PR (before jenkins starts building) or wait for the build to finish before deleting the branch.

**Detailed Version:**
After a very thorough analysis I found out the following: 
- The issue is not with `@octokit/rest` or with the build script in this repo
- The issue is, that the build gets triggered a second time, while the first time is still running. While the first build normally finished successfully, the second one fails because it cannot create a release, because it already exists (created by the first build). Hence also the 'Validation Failed'
- The builds are triggered by webhooks, which can be inspected here (for webapp2018): https://github.com/tadodotcom/webapp2018/settings/hooks 
- Merging the PR and also deleting the branch, both trigger a webhook
- Because the first build (triggered by PR merge) is not finished yet, the second trigger (deleting the branch) thinks that there are still changes that need to be build an queues the second build. 
- So the bug is:
  - that it reacts to changes not relevant to master (deleting a feature branch), even so it is clearly configured to only listen to changes on master.
  - that the seconds build starts, even so at that moment it realizes that there are no changes.

There are several issues open at jenkins that describe this problem (sometime several years old):
- https://issues.jenkins-ci.org/browse/JENKINS-57303?src=confmacro
- https://issues.jenkins-ci.org/browse/JENKINS-54610 
- https://issues.jenkins-ci.org/browse/JENKINS-16513 
- See related issues (in the links) for additional similar issues...

The only workaround that seemed to work was found here:
https://stackoverflow.com/questions/46561344/jenkins-build-triggered-twice-when-merging-branch
Trying it out in the jenkins UI it worked. But after integrating it into the jenkins job builder with 
```
triggers:
    - github
    - pollscm:
          cron: ''
```
it did no work. The result looked the same in the UI, but the build failed. Could be a coincidence or there really is a difference between how jenkins handles changes from ui vs. from jobs builder.

Running out of options and considering the already spend time, we decided to stop here and life with the workaround for now (see at the top).

**Comment by jack-kerouac** [comment]
Good investigation!

Unfortunately, I know all of this and could have just told you. You might in the future want to consider to talk to us about the stuff we built :-).

What we did to prevent that is to configure a 'quiet period' for the job: 10s. If you delete the branch within this quiet period, then it just works and no second build is triggered. Our workflow was to always right after merging (within 10s) to delete the branch.

@weezner, @carusog, @Receks.
